<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="PageFactory" duration-ms="139988" started-at="2020-02-03T08:16:31Z" finished-at="2020-02-03T08:18:51Z">
    <groups>
    </groups>
    <test name="SignIn Test" duration-ms="70239" started-at="2020-02-03T08:16:31Z" finished-at="2020-02-03T08:17:41Z">
      <class name="com.sanqa.testcases.SignInTest">
        <test-method status="PASS" signature="signInTest()[pri:0, instance:com.sanqa.testcases.SignInTest@1c7a252]" name="signInTest" duration-ms="70148" started-at="2020-02-03T13:46:31Z" finished-at="2020-02-03T13:47:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
      </class> <!-- com.sanqa.testcases.SignInTest -->
    </test> <!-- SignIn Test -->
    <test name="Flight Search Test" duration-ms="69715" started-at="2020-02-03T08:17:41Z" finished-at="2020-02-03T08:18:51Z">
      <class name="com.sanqa.testcases.FlightSearchTest">
        <test-method status="FAIL" signature="flightSearchTest()[pri:0, instance:com.sanqa.testcases.FlightSearchTest@385cce]" name="flightSearchTest" duration-ms="69363" started-at="2020-02-03T13:47:41Z" finished-at="2020-02-03T13:48:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [5]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.sanqa.errorcollectors.Errorcollector.assertEquals(Errorcollector.java:37)
	at com.sanqa.errorcollectors.Errorcollector.verifyEquals(Errorcollector.java:101)
	at com.sanqa.testcases.FlightSearchTest.flightSearchTest(FlightSearchTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flightSearchTest -->
      </class> <!-- com.sanqa.testcases.FlightSearchTest -->
    </test> <!-- Flight Search Test -->
  </suite> <!-- PageFactory -->
</testng-results>
